name: highlight-hop
description: A service that converts Kindle highlights from HTML to various formats
runtime:
  name: nodejs
  options:
    typescript: true
    nodeargs: "--experimental-strip-types --no-warnings"
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
  pulumi:autonaming:
    value:
      pattern: ${name}-${project}-${stack}
